---
- name: "UFW management"
  hosts: "all"
  become: true
  gather_facts: true
  tasks:
    # TODO: Install UFW

    # +------------------------------------+
    # |           UNINSTALLATION           |
    # +------------------------------------+

    - name: "UFW | Populate the service facts"
      ansible.builtin.service_facts: {}
      tags: ["uninstall", "ufw-uninstall"]

    - name: "UFW | Stop the service"
      ansible.builtin.service:
        name: "ufw"
        state: "stopped"
        enabled: false
      when: "'ufw.service' in ansible_facts.services"
      tags: ["uninstall", "ufw-uninstall"]

    - name: "UFW | Uninstall the packages using APT"
      ansible.builtin.apt:
        name: ["ufw"]
        state: "absent"
        autoclean: true
        autoremove: true
        purge: true
      when: "ansible_pkg_mgr == 'apt'"

    - name: "UFW | Remove the files and directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "absent"
      loop: ["/etc/ufw", "/etc/default/ufw"]
      tags: ["uninstall", "ufw-uninstall"]

    - name: "UFW | Reload the systemd daemon"
      ansible.builtin.systemd_service:
        daemon_reload: true
      when: "ansible_service_mgr == 'systemd'"
      tags: ["uninstall", "ufw-uninstall"]
...
